# Generated by Django 5.1.3 on 2024-11-20 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='name')),
                ('hp', models.PositiveSmallIntegerField(verbose_name='hit points')),
                ('attack', models.PositiveSmallIntegerField(verbose_name='attack')),
                ('defense', models.PositiveSmallIntegerField(verbose_name='defense')),
                ('special_attack', models.PositiveSmallIntegerField(verbose_name='special attack')),
                ('special_defense', models.PositiveSmallIntegerField(verbose_name='special defense')),
                ('speed', models.PositiveSmallIntegerField(verbose_name='speed')),
                ('legendary', models.BooleanField(default=False, verbose_name='legendary')),
            ],
            options={
                'verbose_name': 'pokemon',
                'verbose_name_plural': 'pokemons',
            },
        ),
    ]
